branches:
  only:
    - master

language: go

go:
  - "1.11"

env:
  - GO111MODULE=on

before_install:
  - make -C swe

before_script:
  - go get honnef.co/go/tools/cmd/staticcheck

script:
  - go test -v -race
  - go vet ./...
  - staticcheck ./...
